/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AdmirCarousel3d {
        "height": number;
        "items": string;
        "iterationCount": number;
        "width": number;
    }
}
declare global {
    interface HTMLAdmirCarousel3dElement extends Components.AdmirCarousel3d, HTMLStencilElement {
    }
    var HTMLAdmirCarousel3dElement: {
        prototype: HTMLAdmirCarousel3dElement;
        new (): HTMLAdmirCarousel3dElement;
    };
    interface HTMLElementTagNameMap {
        "admir-carousel-3d": HTMLAdmirCarousel3dElement;
    }
}
declare namespace LocalJSX {
    interface AdmirCarousel3d {
        "height"?: number;
        "items"?: string;
        "iterationCount"?: number;
        "width"?: number;
    }
    interface IntrinsicElements {
        "admir-carousel-3d": AdmirCarousel3d;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "admir-carousel-3d": LocalJSX.AdmirCarousel3d & JSXBase.HTMLAttributes<HTMLAdmirCarousel3dElement>;
        }
    }
}
